### ISSUE TITLE
Issues with character sheet editing and appearing

### ISSUE THREAD

**Issue by claymanryan** [foundryvtt-dcc/mcc-classes#25]
Currently running into issues while running as a module for Foundry VTT Version 12 Build 329.
Assigning actors with the MCC Sheets works initially, but things like Equipment and mutations, which have an 'add' button, do not function properly. Once the sheets for those actors are closed, they cannot be reopened by clicking on the actors like normal. The program menu that is usually brought up with the esc key also failed to appear once the sheets are opened and closed.

The  three package warnings listed for the module are as follows:

module "mcc-classes" contains "system" which is deprecated in favor of "relationships.systems"
The module "mcc-classes" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
The "MCC Sheets" module's manifest contained the following unknown keys: "author"

Hope this helps to resolve the issues! This module would be super helpful to me if it gets into working order. Thank you for working on this!

**Comment by algnc** [comment]
Can you update and try it again? I think it is working for me.

**Comment by jluebbering** [comment]
I am still having the issue after the latest pull.  DCC version 0.50.5, Foundry 12 Stable Build 331
MCC Sheets is showing 0.1.16

**Comment by algnc** [comment]
Are you self hosted or on Forge? Are you running any other modules?

**Comment by jluebbering** [comment]
Self-hosted.  The only ever module ever on that world was a dice roller, which I disabled for sake of surety.

**Comment by jluebbering** [comment]
Added information:   After the actor is corrupted, if you go to the "configure ownership menu", then "sheets", change the sheet to "generic", it will open again (obviously without any of the custom sheet contents).

ETA:  Checking the Generic sheet, there are now multiple blank "New Spell" entries.  If, and only if, I delete all of those, the sheet will open again if I change it back to Mutant.  It will again fail when adding a mutation.

**Comment by algnc** [comment]
OK, we are trying to reproduce it but are unable to so far.

**Comment by algnc** [comment]
Can you update again and try it?

**Comment by jluebbering** [comment]
I am still testing, but I have not been able to break it again since 1.1.17

Thank you!  I bought Foundry just to run this campaign and I definitely underestimated the headache I was procuring.  It's blown up on us every session, and I just figured out why last night while futzing with it.

Now if someone can just tell me an easy way to get the mutations imported without having to type them all into Spells and Rollable tables by hand, I'll be set!  :)
